### PR TITLE
bootloader installation: fix use of unassigned variable

### PR DESCRIPTION
**Pull request by kbucheli**
the installation of KAOS did not work until I fixed the bootloader installation

### CODE REVIEW

**Comment by demmm** [comment]
Full installation logs needed & full disk setups (before and after installing) including the set flag on the EFI partition of both failed and successful installs.

**Comment by kbucheli** [comment]
Just out of my memory:
- I first tried with first partition ext4 and and second partition swap, then it failed at that location with the error of using an unsigned variable.
- Being a programmer (not python though) I realized immediately that this line should be in the loop.
- On my next attempt I read the hint about the EFI partition I was missing, so I added this one too (I guess as first partition). Now the installation works.
- It may work if the first partition is the EFI partition and if python does not have proper lexical scoping. But it will definitively not work if the EFI partition is not the first one.
- Anyway it would be nice if a missing EFI partition would trigger a more user friendly warning.

**Comment by demmm** [comment]
Sorry, without proper logs showing the actual fails and success this won't be merged.
Current way of setting the EFI flag is tested hundreds of times, used tens of thousands of times and numerous installation logs show it works as intended.
Adding additional info/warnings for missing EFI partition will be implemented.

**Comment by philmmanjaro** [comment]
Well, upstream we have it like this:

```

def prepare_bootloader(fw_type):
    """ Prepares bootloader and set proper flags to EFI boot partition (esp,boot).
    Based on value 'efi_boot_loader', it either calls systemd-boot or grub to be installed.
    :param fw_type:
    :return:
    """
    efi_boot_loader = libcalamares.job.configuration["efiBootLoader"]
    efi_directory = libcalamares.globalstorage.value("efiSystemPartition")

    if fw_type == "efi":
        partitions = libcalamares.globalstorage.value("partitions")
        boot_p = ""
        device = ""

        for partition in partitions:
            if partition["mountPoint"] == efi_directory:
                boot_device = partition["device"]
                boot_p = boot_device[-1:]
                device = boot_device[:-1]

                if not boot_p or not device:
                    return ("EFI directory \"{!s}\" not found!",
                            "Boot partition: \"{!s}\"",
                            "Boot device: \"{!s}\"".format(efi_directory, boot_p, device))
                else:
                    print("EFI directory: \"{!s}\"".format(efi_directory))
                    print("Boot partition: \"{!s}\"".format(boot_p))
                    print("Boot device: \"{!s}\"".format(device))
        print("Set 'EF00' flag")
        subprocess.call(["sgdisk", "--typecode={!s}:EF00".format(boot_p), "{!s}".format(device)])

    if efi_boot_loader == "systemd-boot" and fw_type == "efi":
        install_systemd_boot(efi_directory)
    else:
        install_grub(efi_directory, fw_type)
```

**Comment by demmm** [comment]
No further response for needed logs, can't be merged as is anyway, closing

**Pull request closed without merging**
